Visma-Consulting/react-jsonschema-form

- packages/core/src/components/fields/ArrayField.js
[Please describe them here]
If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).
> KEHFORM-414: Fix accept when multiple files

- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
[Please describe them here]
If this is related to existing tickets, include links to them as well. Use the syntax `fixes #[issue number]` (ex: `fixes #123`).
> KEHFORM-369: Fix missing labels

- packages/core/src/components/Form.js
- packages/core/src/components/fields/SchemaField.js
- Increase delay to update parent field
- Await pending updates on submit
> Optimizing large forms:

- packages/material-ui/src/FileWidget/FileWidget.tsx
> Remove uploaded file

- packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx
- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
> Add FormControl to all checkboxes and radiobuttons

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Fix missing * when field is required

- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Remove labels that are not needed

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/IconButton/IconButton.tsx
> Accessible buttons for list

- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
[KEHFORM-518](https://jira.vismaconsulting.fi/browse/KEHFORM-518) korjaus
> Add legends to fieldsets

- packages/material-ui/src/TextWidget/TextWidget.tsx
- packages/material-ui/src/TextareaWidget/TextareaWidget.tsx
> Fix undefined in character counter

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Add aria-label to title when field is required

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/FileWidget/FileWidget.tsx
- packages/material-ui/src/IconButton/IconButton.tsx
> Add missing button labels

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/material-ui/src/ErrorList/ErrorList.tsx
> Localize errors-title

- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
- packages/material-ui/src/RangeWidget/RangeWidget.tsx
> Fix problem with missing labels

- packages/material-ui/src/FileWidget/FileWidget.tsx
- packages/material-ui/src/SelectWidget/SelectWidget.tsx
> Missing form labels

- packages/core/src/components/Form.js
Poistettu rivinvaihdon disablointi monirivisestä tekstikentästä
> KEHFORM-654

- packages/core/lang/sv-SE.json
> Fix swedish translation

- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Indentation for filtered fields

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
> Add indentation to arrayfields

- packages/material-ui/src/RangeWidget/RangeWidget.tsx
> Scale labels

- packages/material-ui/src/TextWidget/TextWidget.tsx
> Remove banned characters on change

- packages/core/src/components/fields/StringField.js
Formdatan korjaus päivämäärä kysymystä vaihdettaessa toistettavasta ei toistettavaan.
> KEHFORM-824

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/ErrorList/ErrorList.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
- packages/material-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx
- packages/material-ui/src/TitleField/TitleField.tsx
> Accessibility headers

- packages/material-ui/src/FileWidget/FileWidget.tsx
> KEHFORM-778

- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Accessibility headers fixes

- packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx
Kysymyksien otsikossa oleva pakollisuus merkin näkyvyys korjattu totuusarvo ja suostumus tyyppisille kysymyksille.
> KEHFORM-869

- packages/core/src/validate.js
> Remove key from error messages

- packages/core/src/components/fields/SchemaField.js
Päivämäärähaarukan pakollisuuden toteutus
> KEHFORM-898

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Header level fixes

- packages/core/src/validate.js
[KEHFORM-569](https://jira.vismaconsulting.fi/browse/KEHFORM-569)
> Formgroup validation fix

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/material-ui/src/ErrorList/ErrorList.tsx
> Error scrolling id

- packages/core/src/validate.js
> Fix table validation

- packages/core/src/components/fields/SchemaField.js
Toistettavan liitetiedoston kuvaustekstin korjaus
> KEHFORM-934

- packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
Lisätty puuttuvia kuvaustekstejä päivämäärähaarukkaan, totuusarvoon ja valinta kysymykseen.
> KEHFORM-1056

- packages/material-ui/src/FileWidget/FileWidget.tsx
Changed document-object references
> KEHFORM-1065

- packages/material-ui/src/FileWidget/FileWidget.tsx
- packages/material-ui/src/SelectWidget/SelectWidget.tsx
- packages/material-ui/src/TextWidget/TextWidget.tsx
- packages/material-ui/src/TextareaWidget/TextareaWidget.tsx
> Fix empty labels

- packages/core/src/validate.js
> Require at least one

- packages/core/src/utils.js
Korjattu toistettavan tiedostokysymyksen lähetys ongelmia
> KEHFORM-1148

- packages/core/src/utils.js
> KEHFORM-1164

- packages/core/src/components/fields/ArrayField.js
Lisätty tarkastus elementtien poistoon mikä estää määrän menemästä alle minimitoistojen.
> KEHFORM-1179

- packages/material-ui/src/RadioWidget/RadioWidget.tsx
- packages/material-ui/src/SelectWidget/SelectWidget.tsx
> Add scores to select and radiogroup

- packages/core/src/validate.js
> HandleFalseAsUndefined

- packages/core/src/validate.js
> Remove non field elements from validation

- packages/material-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx
> Duplicate labels in formgroup array

- packages/core/src/validate.js
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
[KEHFORM-1235](https://jira.vismaconsulting.fi/browse/KEHFORM-1235)
> AnyOf error formatting

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
[KEHFORM-1201](https://jira.vismaconsulting.fi/browse/KEHFORM-1201), [KEHFORM-1205](https://jira.vismaconsulting.fi/browse/KEHFORM-1205)
> Accessibility components and required

- packages/core/index.d.ts
- packages/core/src/utils.js
- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx
- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
- packages/material-ui/src/FileWidget/FileWidget.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
- packages/material-ui/src/RangeWidget/RangeWidget.tsx
- packages/material-ui/src/SelectWidget/SelectWidget.tsx
- packages/material-ui/src/TextWidget/TextWidget.tsx
- packages/material-ui/src/TextareaWidget/TextareaWidget.tsx
[KEHFORM-1201](https://jira.vismaconsulting.fi/browse/KEHFORM-1201)
> Accessibility required labels

- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
Konffattava nappi kysymyselementti
> KEHFORM-1269

- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
[KEHFORM-818](https://jira.2day.fi/browse/KEHFORM-818)
> Incremental indentation

- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/SelectWidget/SelectWidget.tsx
[KEHFORM-1295](https://jira.2day.fi/browse/KEHFORM-1295)
> KEHFORM-1295: Add logic for scores in multichoice fields

- packages/material-ui/src/RangeWidget/RangeWidget.tsx
> Use 0.5 as step when step is < 1

- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
> Add margin to labels

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/validate.js
> Remove filtered fields from validation

- packages/core/index.d.ts
- packages/core/src/utils.js
- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/SelectWidget/SelectWidget.tsx
- packages/material-ui/src/TextWidget/TextWidget.tsx
- packages/material-ui/src/TextareaWidget/TextareaWidget.tsx
KEHFORM-1099, KEHFORM-1100, KEHFORM-1211, KEHFORM-1213
> Accessibility audit fixes

- packages/material-ui/src/RangeWidget/RangeWidget.tsx
> Slider marks

- packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx
- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
> Aria-describedby

- packages/material-ui/src/TextWidget/TextWidget.tsx
> NumberOfDecimals

- packages/material-ui/src/CheckboxWidget/CheckboxWidget.tsx
- packages/material-ui/src/CheckboxesWidget/CheckboxesWidget.tsx
- packages/material-ui/src/RadioWidget/RadioWidget.tsx
> Accessibility aria-describedby

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
> Editor elements pagination

- packages/core/src/utils.js
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Sähköposti vahvistuksella

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/core/src/utils.js
- packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx
- packages/material-ui/src/FieldTemplate/FieldTemplate.tsx
> Pagination local storage

- packages/core/lang/fi-FI.json
- packages/core/lang/sv-SE.json
- packages/material-ui/src/FileWidget/FileWidget.tsx
[KEHFORM-1495](https://jira.2day.fi/browse/KEHFORM-1495)
> Allowed characters in filename
